openapi: 3.0.0
info:
  title: Posts API
  description: API for managing posts
  version: 1.0.0

paths:
  /posts:
    get:
      summary: Get all posts
      description: Retrieve a list of posts sorted by id in descending order.
      operationId: getPosts
      security:
        - cookieAuth: []
      responses:
        '200':
          description: A list of posts
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Post'
              examples:
                posts:
                  value:
                    - id: 1
                      title: First Post
                      body: This is the first post.
                      user_id: 1
                      username: user1
                      created_at: 2021-01-01T00:00:00Z
                      updated_at: 2021-01-01T00:00:00Z
                    - id: 2
                      title: Second Post
                      body: This is the second post.
                      user_id: 2
                      username: user2
                      created_at: 2021-01-02T00:00:00Z
                      updated_at: 2021-01-02T00:00:00Z
                    - id: 3
                      title: Third Post
                      body: This is the third post.
                      user_id: 3
                      username: user3
                      created_at: 2021-01-03T00:00:00Z
                      updated_at: 2021-01-03T00:00:00Z
                    - id: 4
                      title: Fourth Post
                      body: This is the fourth post.
                      user_id: 4
                      username: user4
                      created_at: 2021-01-04T00:00:00Z
                      updated_at: 2021-01-04T00:00:00Z
                    - id: 5
                      title: Fifth Post
                      body: This is the fifth post.
                      user_id: 5
                      username: user5
                      created_at: 2021-01-05T00:00:00Z
                      updated_at: 2021-01-05T00:00:00Z
      tags:
        - Posts

  /signup:
    post:
      summary: Sign up a new user
      description: Create a new user by providing a username and password.
      operationId: signupUser
      requestBody:
        description: User credentials needed for signing up
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
              required:
                - username
                - password
      responses:
        '201':
          description: Details of the created user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
        '400':
          description: Sign-up failed
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
              examples:
                message:
                  value:
                    "this username is already exists"
      tags:
        - Auth

  /signin:
    post:
      summary: Sign in an existing user
      description: Authenticate a user by providing a username and password.
      operationId: signinUser
      requestBody:
        description: User credentials needed for signing in
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
              required:
                - username
                - password
      responses:
        '200':
          description: Details of the authenticated user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
        '400':
          description: Sign-in failed
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
      tags:
        - Auth

  /signout:
    post:
      summary: sign out an existing user
      description: sign out a user.
      operationId: signoutUser
      responses:
        '204':
          description: Delete authorization cookie
      tags:
        - Auth

components:
  schemas:
    Post:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: Unique identifier for the Post
        title:
          type: string
          description: Title of the Post
        body:
          type: string
          description: Body of the Post
        user_id:
          type: integer
          format: int64
          description: Identifier for the User who created the Post
        username:
          type: string
          description: Username of the User who created the Post
        created_at:
          type: string
          format: date-time
          description: Date and time when the Post was created
        updated_at:
          type: string
          format: date-time
          description: Date and time when the Post was last updated
      required:
        - id
        - title
        - body
        - user_id
        - username
        - created_at
        - updated_at

    UserResponse:
      type: object
      properties:
        user:
          type: object
          properties:
            id:
              type: integer
              format: int64
              description: Unique identifier for the User
            username:
              type: string
              description: Username of the User
          required:
            - id
            - username
  
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: Authorization  # cookie name

tags:
  - name: Posts
    description: Operations related to posts
  - name: Auth
    description: Authentication operations