openapi: 3.0.0
info:
 title: Posts API
 description: API for managing posts
 version: 1.0.0

paths:
 /posts:
   get:
     summary: Get all posts
     description: Retrieve a list of posts sorted by id in descending order.
     operationId: getPosts
     responses:
       '200':
         description: A list of posts
         content:
           application/json:
             schema:
               type: array
               items:
                 $ref: '#/components/schemas/Post'
             examples:
                posts:
                  value:
                    - id: 1
                      title: First Post
                      body: This is the first post.
                      user_id: 1
                      username: user1
                      created_at: 2021-01-01T00:00:00Z
                      updated_at: 2021-01-01T00:00:00Z
                    - id: 2
                      title: Second Post
                      body: This is the second post.
                      user_id: 2
                      username: user2
                      created_at: 2021-01-02T00:00:00Z
                      updated_at: 2021-01-02T00:00:00Z
                    - id: 3
                      title: Third Post
                      body: This is the third post.
                      user_id: 3
                      username: user3
                      created_at: 2021-01-03T00:00:00Z
                      updated_at: 2021-01-03T00:00:00Z
                    - id: 4
                      title: Fourth Post
                      body: This is the fourth post.
                      user_id: 4
                      username: user4
                      created_at: 2021-01-04T00:00:00Z
                      updated_at: 2021-01-04T00:00:00Z
                    - id: 5
                      title: Fifth Post
                      body: This is the fifth post.
                      user_id: 5
                      username: user5
                      created_at: 2021-01-05T00:00:00Z
                      updated_at: 2021-01-05T00:00:00Z
     tags:
       - Posts

components:
 schemas:
   Post:
     type: object
     properties:
       id:
         type: integer
         format: int64
         description: Unique identifier for the Post
       title:
         type: string
         description: Title of the Post
       body:
         type: string
         description: Body of the Post
       user_id:
         type: integer
         format: int64
         description: Identifier for the User who created the Post
       username:
         type: string
         description: Username of the User who created the Post
       created_at:
         type: string
         format: date-time
         description: Date and time when the Post was created
       updated_at:
         type: string
         format: date-time
         description: Date and time when the Post was last updated
     required:
       - id
       - title
       - body
       - user_id
       - username
       - created_at
       - updated_at

tags:
 - name: Posts
   description: Operations related to posts
