openapi: 3.0.0
info:
 title: Posts API
 description: API for managing posts
 version: 1.0.0

paths:
 /posts:
   get:
     summary: Get all posts
     description: Retrieve a list of posts sorted by id in descending order.
     operationId: getPosts
     responses:
       '200':
         description: A list of posts
         content:
           application/json:
             schema:
               type: array
               items:
                 $ref: '#/components/schemas/Post'
     tags:
       - Posts

components:
 schemas:
   Post:
     type: object
     properties:
       id:
         type: integer
         format: int64
         description: Unique identifier for the Post
       title:
         type: string
         description: Title of the Post
       body:
         type: string
         description: Body of the Post
       user_id:
         type: integer
         format: int64
         description: Identifier for the User who created the Post
       username:
         type: string
         description: Username of the User who created the Post
       created_at:
         type: string
         format: date-time
         description: Date and time when the Post was created
       updated_at:
         type: string
         format: date-time
         description: Date and time when the Post was last updated
     required:
       - id
       - title
       - body
       - user_id
       - username
       - created_at
       - updated_at

tags:
 - name: Posts
   description: Operations related to posts
