openapi: 3.0.0
info:
  title: Posts API
  description: API for managing posts
  version: 1.0.0

paths:
  /posts:
    get:
      summary: Get all posts
      description: Retrieve a list of posts sorted by id in descending order.
      operationId: getPosts
      security:
        - cookieAuth: []
      parameters:
        - in: query
          name: limit
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 20
          description: Number of posts to return
        - in: query
          name: offset
          schema:
            type: integer
            minimum: 0
            default: 0
          description: Number of posts to skip
      responses:
        '200':
          description: A list of posts
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Post'
              examples:
                posts:
                  value:
                    - id: 1
                      title: First Post
                      body: This is the first post.
                      user_id: 1
                      username: user1
                      created_at: 2021-01-01T00:00:00Z
                      updated_at: 2021-01-01T00:00:00Z
                    - id: 2
                      title: Second Post
                      body: This is the second post.
                      user_id: 2
                      username: user2
                      created_at: 2021-01-02T00:00:00Z
                      updated_at: 2021-01-02T00:00:00Z
                    - id: 3
                      title: Third Post
                      body: This is the third post.
                      user_id: 3
                      username: user3
                      created_at: 2021-01-03T00:00:00Z
                      updated_at: 2021-01-03T00:00:00Z
                    - id: 4
                      title: Fourth Post
                      body: This is the fourth post.
                      user_id: 4
                      username: user4
                      created_at: 2021-01-04T00:00:00Z
                      updated_at: 2021-01-04T00:00:00Z
                    - id: 5
                      title: Fifth Post
                      body: This is the fifth post.
                      user_id: 5
                      username: user5
                      created_at: 2021-01-05T00:00:00Z
                      updated_at: 2021-01-05T00:00:00Z
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Unauthorized"
      tags:
        - Posts
    
    post:
      summary: Create a new post
      description: Create a new post by providing a title and body.
      operationId: createPost
      security:
        - cookieAuth: []
      requestBody:
        description: Post details needed for creation
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  maxLength: 100
                body:
                  type: string
              required:
                - title
                - body
      responses:
        '201':
          description: Created Post entity
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'
      tags:
        - Posts

  /posts/{postId}:
    get:
      summary: Get a post by ID
      description: Retrieve a post by its ID.
      operationId: getPost
      security:
        - cookieAuth: []
      parameters:
        - in: path
          name: postId
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Post entity
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'
      tags:
        - Posts

    put:
      summary: Update a post
      description: Update an existing post by providing a title and body.
      operationId: updatePost
      security:
        - cookieAuth: []
      parameters:
        - in: path
          name: postId
          required: true
          schema:
            type: integer
      requestBody:
        description: Post details needed for update
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  maxLength: 100
                body:
                  type: string
      responses:
        '200':
          description: Updated Post entity
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'
        '400':
          description: You are not the author of the post
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Unauthorized to update this post"
      tags:
        - Posts

    delete:
      summary: Delete a post
      description: Delete an existing post by its ID (logical deletion by setting `deleted_at`).
      operationId: deletePost
      security:
        - cookieAuth: []
      parameters:
        - in: path
          name: postId
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: No Content
        '400':
          description: You are not the author of the post
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Unauthorized to delete this post"
      tags:
        - Posts

  /posts/{postId}/comments:
    get:
      summary: Get all comments for a post
      description: Retrieve a list of comments for a post sorted by id in descending order.
      operationId: getComments
      security:
        - cookieAuth: []
      parameters:
        - in: path
          name: postId
          required: true
          schema:
            type: integer
        - in: query
          name: limit
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 20
          description: Number of comments to return
        - in: query
          name: offset
          schema:
            type: integer
            minimum: 0
            default: 0
          description: Number of comments to skip
      responses:
        '200':
          description: A list of comments
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Comment'
              examples:
                comments:
                  value:
                    - id: 1
                      body: First Comment
                      user_id: 1
                      username: user1
                      created_at: 2021-01-01T00:00:00Z
                      updated_at: 2021-01-01T00:00:00Z
                    - id: 2
                      body: Second Comment
                      user_id: 2
                      username: user2
                      created_at: 2021-01-02T00:00:00Z
                      updated_at: 2021-01-02T00:00:00Z
                    - id: 3
                      body: Third Comment
                      user_id: 3
                      username: user3
                      created_at: 2021-01-03T00:00:00Z
                      updated_at: 2021-01-03T00:00:00Z

    post:
      summary: Create a new comment
      description: Create a new comment for a post by providing a body.
      operationId: createComment
      security:
        - cookieAuth: []
      requestBody:
        description: Comment details needed for creation
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                body:
                  type: string
              required:
                - body
      responses:
        '201':
          description: Created Comment entity
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Comment'

  /posts/{postId}/comments/{commentId}:
    get:
      summary: Get a comment by ID
      description: Retrieve a comment by its ID.
      operationId: getComment
      security:
        - cookieAuth: []
      parameters:
        - in: path
          name: postId
          required: true
          schema:
            type: integer
        - in: path
          name: commentId
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Comment entity
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Comment'

    put:
      summary: Update a comment
      description: Update an existing comment by providing a body.
      operationId: updateComment
      security:
        - cookieAuth: []
      parameters:
        - in: path
          name: postId
          required: true
          schema:
            type: integer
        - in: path
          name: commentId
          required: true
          schema:
            type: integer
      requestBody:
        description: Comment details needed for update
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                body:
                  type: string
      responses:
        '200':
          description: Updated Comment entity
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Comment'
        '400':
          description: You are not the author of the comment
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Unauthorized to update this comment"

    delete:
      summary: Delete a comment
      description: Delete an existing comment by its ID (logical deletion by setting `deleted_at`).
      operationId: deleteComment
      security:
        - cookieAuth: []
      parameters:
        - in: path
          name: postId
          required: true
          schema:
            type: integer
        - in: path
          name: commentId
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: No Content
        '400':
          description: You are not the author of the comment
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

  /signup:
    post:
      summary: Sign up a new user
      description: Create a new user by providing a username and password.
      operationId: signupUser
      requestBody:
        description: User credentials needed for signing up
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
              required:
                - username
                - password
      responses:
        '201':
          description: Details of the created user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
        '400':
          description: Sign-up failed
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
              examples:
                message:
                  value:
                    "Duplicate User"
      tags:
        - Auth

  /signin:
    post:
      summary: Sign in an existing user
      description: Authenticate a user by providing a username and password.
      operationId: signinUser
      requestBody:
        description: User credentials needed for signing in
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
              required:
                - username
                - password
      responses:
        '200':
          description: Details of the authenticated user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
        '400':
          description: Sign-in failed
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Signin failed"
      tags:
        - Auth

  /signout:
    post:
      summary: sign out an existing user
      description: sign out a user.
      operationId: signoutUser
      security:
        - cookieAuth: []
      responses:
        '204':
          description: Delete authorization cookie
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Unauthorized"
      tags:
        - Auth

  /user:
    get:
      summary: Get signed-in user
      description: get signed-in user.
      operationId: getSignedInUser
      security:
        - cookieAuth: []
      responses:
        '200':
          description: Details of the signed-in user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Unauthorized"
      tags:
        - Auth

components:
  schemas:
    Post:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: Unique identifier for the Post
        title:
          type: string
          description: Title of the Post
        body:
          type: string
          description: Body of the Post
        user_id:
          type: integer
          format: int64
          description: Identifier for the User who created the Post
        username:
          type: string
          description: Username of the User who created the Post
        created_at:
          type: string
          format: date-time
          description: Date and time when the Post was created
        updated_at:
          type: string
          format: date-time
          description: Date and time when the Post was last updated
      required:
        - id
        - title
        - body
        - user_id
        - username
        - created_at
        - updated_at

    Comment:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: Unique identifier for the Comment
        body:
          type: string
          description: Body of the Comment
        user_id:
          type: integer
          format: int64
          description: Identifier for the User who created the Comment
        username:
          type: string
          description: Username of the User who created the Comment
        created_at:
          type: string
          format: date-time
          description: Date and time when the Comment was created
        updated_at:
          type: string
          format: date-time
          description: Date and time when the Comment was last updated
      required:
        - id
        - body
        - user_id
        - username
        - created_at
        - updated_at

    UserResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: Unique identifier for the User
        username:
          type: string
          description: Username of the User
      required:
        - id
        - username
  
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: Authorization  # cookie name

tags:
  - name: Posts
    description: Operations related to posts
  - name: Auth
    description: Authentication operations