name: Test Backend

on:
  push:
    # paths:
    #   - 'backend/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    container: golang:1.22

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Run staticcheck
        working-directory: ./backend
        run: staticcheck ./...

  test:
    runs-on: ubuntu-latest
    container: golang:1.22
    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: training
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run test
        working-directory: ./backend
        run: go test ./test/... -race -vet=off