name: Test Backend

on:
  push:
    # paths:
    #   - 'backend/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    container: golang:1.22

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Run staticcheck
        run: staticcheck ./backend/...

  test:
    runs-on: ubuntu-latest
    container: golang:1.22

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Run test
        run: go test ./... -race -vet=off