name: Test Backend

on:
  push:
    # paths:
    #   - 'backend/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    container: golang:1.22

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Run staticcheck
        working-directory: ./backend
        run: staticcheck ./...

  test:
    runs-on: ubuntu-latest
    container: golang:1.22

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run test
        working-directory: ./backend
        run: go test ./test/... -race -vet=off